export const types = Object.freeze({
  // Sync
  PIZZAS_SET_PIZZAS: 'SET_PIZZAS',
  PIZZAS_START_FETCHING: 'PIZZAS_START_FETCHING',
  PIZZAS_ST0P_FETCHING: 'PIZZAS_ST0P_FETCHING',
  PIZZAS_FETCHING_ERROR: 'PIZZAS_FETCHING_ERROR',
  PIZZAS_SET_LOADED: 'PIZZAS_SET_LOADED',
  // Async
  PIZZAS_FETCH_PIZZAS_ASYNC: 'PIZZAS_FETCH_PIZZAS_ASYNC',
});
