export const types = Object.freeze({
  CART_SET_TOTAL_PRICE: 'CART_SET_TOTAL_PRICE',
  CART_SET_TOTAL_COUNT: 'CART_SET_TOTAL_COUNT',
  CART_ADD_PIZZA_TO_CART: 'CART_ADD_PIZZA_TO_CART',
  CART_CLEAR_CART: 'CART_CLEAR_CART',
  CART_REMOVE_CART_ITEM: 'CART_REMOVE_CART_ITEM',
})